"""Adding some attributes to Artist and Venue

Revision ID: 15545659a11e
Revises: 7e7094e04e35
Create Date: 2021-03-02 03:27:03.067236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15545659a11e'
down_revision = '7e7094e04e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('venues', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'seeking_description')
    op.drop_column('artists', 'seeking_venue')
    op.drop_column('artists', 'seeking_description')
    # ### end Alembic commands ###
